export const MCP_LIMITS = {
  MAX_QUERY_LENGTH: 200,
  MAX_RESULTS_PER_PAGE: 20,
  MAX_TAGS_PER_QUERY: 5,
  MAX_TAG_LENGTH: 30,
  MAX_ID_LENGTH: 100,
  MAX_RESPONSE_PAYLOAD_SIZE_BYTES: 1024 * 1024 * 2, // 2MB
  REPOSITORY_TIMEOUT_MS: 5000,
} as const;
